### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by alvinayeung** [csoutter/escape580#4]
This was such a fun game! It was such a creative idea. One thing that I noticed: I 'tabbed' on the last answer option which was a wrong answer and my intention was to 'tab' back to the first answer option but instead it went through all of my chrome tabs and buttons. Is there a way to click tab from the last answer back to the first answer option straightaway?

**Comment by csoutter** [comment]
Thank you so much for the feedback, Alvina! We were unable to replicate this, unfortunately, so hopefully, this won't happen again! :)
