### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by braxhawk** [csoutter/escape580#5]
Not sure if you're able to see my eval, so I put the full one in here! I really enjoyed the game! For the most part, it ran very smoothly, and I found the game both fun and just the right amount of challenging. I didn't use my laptops VoiceOver, and just went with the audio given by, what I assume was, the text-to-speech API. The music was also a great addition, and didn't distract me from the game itself, and was very enjoyable. Some issues I ran into and some suggestions: 
- On Safari, pressing tab did not work for me. Upon pressing tab, it would want me to type in the search bar
- On Chrome, all of the controls worked well, however, if I wanted to loop back to the first answer choice, it would go to the search bar before going to the first answer choice
- I think adding a button that allows you to hear the riddle, instructions, or questions again would be a nice addition, as some of them were very long

Overall, an awesome project!

**Comment by csoutter** [comment]
Hey, Braxton! Thank you so much for your feedback! We have updated our game and instructions to incorporate your feedback, especially adding options to repeat instructions :) You're the best!
